<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-DevSkill.Inventory.Web-6fad8404-27dd-4c14-9ec6-599166ad157d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\images\products\61481fa1-7c81-486e-bf2f-28728018067f.png" />
    <Content Remove="wwwroot\images\products\b56225ba-b1ed-4fc9-aaf6-9d23c1ad670b.jfif" />
    <Content Remove="wwwroot\images\products\de35b88e-fdf3-482e-81ea-b4b5080a2c3a.png" />
    <Content Remove="wwwroot\images\products\e272905d-ae3e-47c3-bd57-26433eb7b202.png" />
    <Content Remove="wwwroot\images\products\f1a1d885-8328-465e-8329-4b38b5c15020.jfif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.3.1" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.0.12" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
	 <PackageReference Include="Cortex.Mediator" Version="1.7.0" />
	 <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.2.0" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	  <PackageReference Include="System.Drawing.Common" Version="9.0.6" />
	  <PackageReference Include="ZXing.Net" Version="0.16.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
    <Folder Include="wwwroot\images\customers\" />
    <Folder Include="wwwroot\images\barcodes\" />
    <Folder Include="wwwroot\scss\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\products\61481fa1-7c81-486e-bf2f-28728018067f.png" />
    <None Include="wwwroot\images\products\b56225ba-b1ed-4fc9-aaf6-9d23c1ad670b.jfif" />
    <None Include="wwwroot\images\products\de35b88e-fdf3-482e-81ea-b4b5080a2c3a.png" />
    <None Include="wwwroot\images\products\e272905d-ae3e-47c3-bd57-26433eb7b202.png" />
    <None Include="wwwroot\images\products\f1a1d885-8328-465e-8329-4b38b5c15020.jfif" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevSkill.Inventory.Application\DevSkill.Inventory.Application.csproj" />
    <ProjectReference Include="..\DevSkill.Inventory.Infrastructure\DevSkill.Inventory.Infrastructure.csproj" />
  </ItemGroup>

</Project>
