version: "3"
services:
    web:
        build:
            context: .
            dockerfile: DevSkill.Inventory.Web/Dockerfile
        image: devskill.inventory.web
        env_file:
            - DevSkill.Inventory.Web/web.env
        volumes:
            - devskill-inventory-data:/app/logs/
        ports:
            - "8000:80"
        depends_on:
            - db 
        entrypoint: [ "dotnet" , "DevSkill.Inventory.Web.dll" ]
    db:
      build:
        context: .
        dockerfile: DevSkill.Inventory.Db/Dockerfile
      image: "devskill.inventory.sqlserver"
      env_file:
          - DevSkill.Inventory.Db/db.env
      expose:
          - "1432"
      ports:
          - "1432:1433"
volumes:
    devskill-inventory-data:
      external: true