<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\BalanceTransfers\**" />
    <Compile Remove="Features\Customers\**" />
    <Compile Remove="Features\Sales\**" />
    <Compile Remove="Features\Users\**" />
    <EmbeddedResource Remove="Features\BalanceTransfers\**" />
    <EmbeddedResource Remove="Features\Customers\**" />
    <EmbeddedResource Remove="Features\Sales\**" />
    <EmbeddedResource Remove="Features\Users\**" />
    <None Remove="Features\BalanceTransfers\**" />
    <None Remove="Features\Customers\**" />
    <None Remove="Features\Sales\**" />
    <None Remove="Features\Users\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DevSkill.Core.Domain" Version="9.0.0.6" />
    <Folder Include="Enums\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
