<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DevSkill.Core.Domain" Version="9.0.0.6" />
    <Folder Include="Features\BalanceTransfers\Commands\" />
    <Folder Include="Features\Customers\Commands\" />
    <Folder Include="Features\Sales\Commands\" />
    <Folder Include="Features\Users\Employees\Commands\" />
    <Folder Include="Features\Users\InventoryUsers\Commands\" />
    <Folder Include="Features\Users\Suppliers\Commands\" />
    <Folder Include="Enums\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
